# Generated by Django 2.1 on 2018-08-02 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Haberler', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Logo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('LogoImage', models.ImageField(upload_to='')),
            ],
        ),
    ]
