# Generated by Django 2.1 on 2018-08-03 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Haberler', '0002_logo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'verbose_name_plural': 'Yazı'},
        ),
    ]
