# Generated by Django 2.1 on 2018-08-03 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Haberler', '0003_auto_20180803_1457'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'verbose_name_plural': 'Yazılar'},
        ),
    ]
