# Generated by Django 2.0 on 2018-08-03 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Haberler', '0006_auto_20180803_1648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.ForeignKey(on_delete=None, to='Haberler.Category', verbose_name='Kategori'),
        ),
        migrations.AlterField(
            model_name='article',
            name='sub_category',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=None, to='Haberler.SubCategory', verbose_name='Ebeveyn kategori'),
        ),
    ]
