# Generated by Django 2.0 on 2018-08-03 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Haberler', '0008_auto_20180803_1705'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='source',
            options={'verbose_name_plural': 'Kaynaklar'},
        ),
    ]
