# Generated by Django 2.0 on 2018-08-03 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Haberler', '0009_auto_20180803_1713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='source',
            field=models.ForeignKey(on_delete=None, to='Haberler.Source', verbose_name='Haber Kaynağı'),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Başlık'),
        ),
    ]
