# Generated by Django 2.0 on 2018-08-03 15:11

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Haberler', '0010_auto_20180803_1754'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='industry',
        ),
        migrations.RemoveField(
            model_name='article',
            name='source_url',
        ),
        migrations.AlterField(
            model_name='article',
            name='active',
            field=models.BooleanField(verbose_name='Sıcak Haber'),
        ),
        migrations.AlterField(
            model_name='article',
            name='cover_image',
            field=models.ImageField(upload_to='', verbose_name='Görsel Ekle'),
        ),
        migrations.AlterField(
            model_name='article',
            name='full_text',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Haber Detayı'),
        ),
        migrations.AlterField(
            model_name='article',
            name='hash_tags',
            field=models.ManyToManyField(blank=True, default=None, to='Haberler.HashTag', verbose_name='Etiket'),
        ),
        migrations.AlterField(
            model_name='article',
            name='hot',
            field=models.BooleanField(verbose_name='Flash Haber'),
        ),
        migrations.AlterField(
            model_name='article',
            name='popular',
            field=models.BooleanField(verbose_name='Manşet Haber'),
        ),
        migrations.AlterField(
            model_name='article',
            name='published_on',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Yayınlama Tarihi'),
        ),
    ]
