# Generated by Django 2.0 on 2018-08-04 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Haberler', '0011_auto_20180803_1811'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Logo',
            new_name='Settings',
        ),
    ]
