# Generated by Django 2.0 on 2018-08-03 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CanlıTv', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='canlıtv',
            options={'verbose_name': 'Canlı Tv'},
        ),
    ]
