# Generated by Django 2.0 on 2018-08-03 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CanlıTv', '0002_auto_20180803_1708'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='canlıtv',
            options={'verbose_name_plural': 'Canlı Tv'},
        ),
    ]
